steps:
  # 1. Docker 이미지 빌드 (app 폴더를 컨텍스트로 지정)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/game-sort-service:$SHORT_SHA', '.']
    dir: 'app'

  # 2. Docker 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/game-sort-service:$SHORT_SHA']

  # 3. Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'game-sort-service'
      - '--image=gcr.io/$PROJECT_ID/game-sort-service:$SHORT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,OPENAI_API_KEY=$_OPENAI_API_KEY'
    entrypoint: 'gcloud'

images:
  - 'gcr.io/$PROJECT_ID/game-sort-service:$SHORT_SHA'