steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tag-editor-api', '.']

  # 2. Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tag-editor-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tag-editor-api'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/tag-editor-api'
